### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by michaelneuper** [Hyphen-ated/koreader-calibre-plugin#1]
calibre, version 6.15.1
ERROR: Unhandled exception: <b>TypeError</b>:'&lt;' not supported between instances of 'str' and 'int'

calibre 6.15.1  embedded-python: False
Linux-6.2.10-zen1-1-zen-x86_64-with-glibc2.37 Linux ('64bit', 'ELF')
('Linux', '6.2.10-zen1-1-zen', '#1 ZEN SMP PREEMPT_DYNAMIC Fri, 07 Apr 2023 02:10:16 +0000')
Python 3.10.10
Interface language: None
Successfully initialized third party plugins: Goodreads (1, 7, 6) && KOReader Sync (0, 4, 1) && Kindle Collections (1, 7, 29) && Kindle hi-res covers (0, 5, 0) && Kobo Books (1, 9, 2)
Traceback (most recent call last):
  File "calibre_plugins.koreader.action", line 495, in sync_to_calibre
    value = column['transform'](value)
  File "calibre_plugins.koreader.config", line 116, in <lambda>
    'transform': (lambda d: json.dumps(
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 353, in _iterencode_dict
    items = sorted(dct.items())
TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by Hyphen-ated** [comment]
It looks like you're using upstream version 0.4.1 of this plugin, rather than my fork. So you're in the wrong place. Also there have been two newer releases of upstream since 0.4.1, try updating.
